# Deploy wspólnego kodu na hosting klasy 4Ta (projekt plan4ta -> site plan4ta -> plan4ta.web.app)
name: Deploy plan4ta on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLAN4TA }}
          channelId: live
          projectId: plan4ta
          target: plan4ta
